### ISSUE TITLE
Regarding the preprocess.py

### ISSUE THREAD

**Issue by codeinhere123** [gabriel-dev/rune-breaker#5]
Dear Mr Gabriel,

Good day!

Thanks for the wonderful and detail oriented guide given, I have reach the process of preprocess.py however it keep throwing the problem where "Centroid not found! Returning the center point..." and in the result page, the preprocess couldnt determine the arrow key. Do you mind to shade some light? Apologize if I didn't give enough detail as I'm still relatively new in python and was trying to learn the code for machine learning purpose. 

Attached are some pictures for your reference.
![Screenshot taken](https://user-images.githubusercontent.com/71201805/94362802-60bbbf00-00f0-11eb-88b8-96a37da663fd.png)
![Arrow couldnt detect](https://user-images.githubusercontent.com/71201805/94362804-62858280-00f0-11eb-8178-382a76746779.png)
![Centroid not found issue](https://user-images.githubusercontent.com/71201805/94362805-631e1900-00f0-11eb-9447-73584b0ffdbd.png)

Alternatively, is that possible to communicate via email as I won't be constantly stay connected in github.

Regards
Alex
talkinhere123@gmail.com

**Comment by gbrlfaria** [comment]
Hi, @codeinhere123 

The reason why the preprocessing algorithm is unable to find the centroid of the arrows is because it works based on the surrounding circles of the arrows. Quoting the README:

> Each polygon constitutes a different contour. But then, how to determine which contours belong to the arrow? It turns out that directly identifying the arrow is not the best alternative. Frequently, the obfuscation heavily distorts the outline of the arrow, which makes identifying it very difficult.
>
> Fortunately, some outlines are much simpler to identify: **the circles that surround the arrow**. There are two reasons for this. First, these contours tend to keep their shape intact despite the obfuscation. Second, circumferences have much clearer morphological characteristics.

Unfortunately, these were removed in a recent GMS update, so the locating algorithm used in this project doesn't work anymore. As I said in issue #4, you will have to come up with another method to locate them.

**Comment by codeinhere123** [comment]
Dear Mr Gabriel,

Good day! 

Noted on the above points, really appreciated your response on this matter despite similar issue raised before. You can delete this issue if you wish to just to avoid duplication purpose.

Thanks and wish you have a good days ahead. Will close this issue accordingly. 👍 

Regards
Alex
