### ISSUE TITLE
how to train new runes

### ISSUE THREAD

**Issue by PhoenixNil** [gabriel-dev/rune-breaker#6]
Dear Mr. Gabriel,
  I believe you had already  know runes change(more clear, but seems that Lose contour）so can you give us some new advice about how to Rebuild the model？ I very appreciate you for research in runes

**Comment by gbrlfaria** [comment]
Hello there, Phoenix. Thanks for your issue.

Yes, I'm aware of the recent update to the rune system. You can check out my advice about this topic in [issue #4](https://github.com/gabriel-dev/rune-breaker/issues/4).
