### ISSUE TITLE
The project is great, but I don't know how to use it

### ISSUE THREAD

**Issue by simpleeeeee** [gabriel-dev/rune-breaker#8]
Hello, I am very interested in this project and would like to know the specific use method. Can you tell me? My email address is zuhang.meng@gmail.com

**Comment by gbrlfaria** [comment]
Hello there and thanks for the interest. Sorry for the (very) late response, I have been quite busy in the last months. I believe all the information necessary to reproduce the project is contained in the README. Could you be more specific about your needs (if you haven't figured it out already)?

**Comment by simpleeeeee** [comment]
> 您好，感谢您的关注。抱歉（非常）迟到的回复，过去几个月我一直很忙。我相信重现项目所需的所有信息都包含在自述文件中。您能否更具体地说明您的需求（如果您还没有弄清楚的话）？
